// Vocabulary data for verbal question generation.
// Each antonym entry: [word, opposite, near-synonym-trap, unrelated1, unrelated2]
const ANTONYMS = [
  ['abundant','scarce','plentiful','narrow','damp'],
  ['candid','evasive','honest','cheerful','brief'],
  ['frugal','extravagant','thrifty','cautious','modest'],
  ['ephemeral','permanent','fleeting','ancient','heavy'],
  ['benevolent','malicious','kindly','wealthy','distant'],
  ['diligent','lazy','industrious','clever','quiet'],
  ['lucid','confusing','clear','bright','sudden'],
  ['obsolete','current','outdated','fragile','coarse'],
  ['verbose','concise','wordy','loud','formal'],
  ['volatile','stable','unpredictable','bitter','hollow'],
  ['gregarious','solitary','sociable','generous','alert'],
  ['meticulous','careless','thorough','patient','severe'],
  ['hostile','friendly','aggressive','remote','dense'],
  ['reluctant','eager','hesitant','tired','polite'],
  ['tedious','engaging','dull','lengthy','plain'],
  ['futile','effective','pointless','simple','rigid'],
  ['ambiguous','definite','unclear','complex','mild'],
  ['pragmatic','idealistic','practical','stubborn','sincere'],
  ['novice','expert','beginner','student','rival'],
  ['indifferent','passionate','apathetic','neutral','absent'],
  ['transparent','opaque','clear','flimsy','shallow'],
  ['audacious','timid','bold','rude','swift'],
  ['austere','luxurious','severe','remote','bland'],
  ['coherent','disjointed','logical','audible','earnest'],
  ['compulsory','optional','mandatory','routine','formal'],
  ['conspicuous','hidden','obvious','sizeable','showy'],
  ['deter','encourage','discourage','delay','confuse'],
  ['diminish','increase','reduce','divide','soften'],
  ['dubious','certain','doubtful','shady','minor'],
  ['elated','despondent','joyful','calm','restless'],
  ['erratic','consistent','unpredictable','rapid','faulty'],
  ['exacerbate','alleviate','worsen','provoke','extend'],
  ['fortify','weaken','strengthen','enclose','supply'],
  ['hasten','delay','accelerate','pursue','disturb'],
  ['humble','arrogant','modest','poor','gentle'],
  ['impartial','biased','neutral','distant','formal'],
  ['inept','skilled','incompetent','foolish','awkward'],
  ['innovative','conventional','original','costly','rapid'],
  ['intricate','simple','complex','delicate','curved'],
  ['lenient','strict','permissive','gentle','vague'],
  ['mundane','extraordinary','ordinary','earthly','dreary'],
  ['negligible','significant','trivial','careless','tiny'],
  ['opulent','impoverished','lavish','glossy','spacious'],
  ['placate','provoke','appease','ignore','flatter'],
  ['prudent','reckless','sensible','thrifty','solemn'],
  ['resilient','fragile','tough','elastic','steady'],
  ['scrutinize','skim','examine','criticize','record'],
  ['sporadic','continuous','occasional','scattered','brief'],
  ['squander','conserve','waste','scatter','spend'],
  ['superficial','profound','shallow','glossy','hasty'],
  ['tenacious','yielding','persistent','tough','gripping'],
  ['trivial','crucial','unimportant','common','petty'],
  ['vigilant','careless','watchful','anxious','awake'],
  ['zealous','apathetic','fervent','religious','busy'],
  ['adept','clumsy','skilled','willing','quick'],
  ['affluent','needy','wealthy','flowing','generous'],
  ['brevity','longevity','conciseness','clarity','wit'],
  ['clandestine','overt','secret','illegal','nocturnal'],
  ['docile','unruly','obedient','gentle','dull'],
  ['flourish','wither','thrive','wave','expand']
];

// Each synonym entry: [word, synonym, antonym-trap, unrelated1, unrelated2]
const SYNONYMS = [
  ['ephemeral','fleeting','permanent','heavy','ancient'],
  ['pragmatic','practical','idealistic','stubborn','talkative'],
  ['meticulous','thorough','sloppy','patient','narrow'],
  ['arduous','difficult','effortless','lengthy','dry'],
  ['candid','frank','secretive','cheerful','brief'],
  ['abate','subside','intensify','postpone','collect'],
  ['cordial','friendly','hostile','formal','brief'],
  ['deference','respect','contempt','delay','caution'],
  ['eloquent','articulate','inarticulate','loud','formal'],
  ['feasible','achievable','impossible','costly','simple'],
  ['garrulous','talkative','silent','cheerful','clumsy'],
  ['imminent','impending','distant','severe','obvious'],
  ['lethargic','sluggish','energetic','calm','ill'],
  ['nullify','invalidate','confirm','reduce','delay'],
  ['ostentatious','showy','modest','costly','rigid'],
  ['paramount','supreme','minor','equal','distant'],
  ['quell','suppress','incite','soothe','announce'],
  ['redundant','superfluous','essential','repeated','brief'],
  ['succinct','brief','rambling','clear','sharp'],
  ['tangible','concrete','abstract','touching','visible'],
  ['ubiquitous','widespread','rare','universal','hidden'],
  ['viable','workable','doomed','living','flexible'],
  ['wary','cautious','trusting','tired','clever'],
  ['adamant','insistent','flexible','hard','angry'],
  ['benign','harmless','malignant','pleasant','mild'],
  ['concur','agree','dissent','run','arrive'],
  ['despondent','dejected','elated','tired','quiet'],
  ['exemplary','outstanding','inferior','typical','instructive'],
  ['frivolous','trivial','serious','playful','costly'],
  ['hinder','impede','assist','follow','conceal']
];

// Analogy relationship families. Each: {rel, pairs:[[a,b],...], distractorPool:[...]}
const ANALOGY_FAMILIES = [
  { rel:'form a group called a', label:'collective noun',
    pairs:[['wolves','pack'],['birds','flock'],['fish','school'],['cattle','herd'],['lions','pride'],['bees','swarm'],['puppies','litter'],['geese','gaggle']],
    distractors:['den','burrow','nest','forest','howl','migration','hive','cage'] },
  { rel:'has a young called a', label:'young of',
    pairs:[['dog','puppy'],['cat','kitten'],['horse','foal'],['sheep','lamb'],['cow','calf'],['goat','kid'],['duck','duckling'],['bear','cub']],
    distractors:['stable','kennel','barn','pasture','wool','saddle','pond','forest'] },
  { rel:'works with a tool called a',
    pairs:[['carpenter','hammer'],['surgeon','scalpel'],['chef','knife'],['painter','brush'],['gardener','spade'],['tailor','needle'],['barber','scissors'],['blacksmith','anvil']],
    distractors:['hospital','kitchen','canvas','garden','fabric','salon','forge','workshop'] },
  { rel:'works in a',
    pairs:[['teacher','classroom'],['judge','courtroom'],['pilot','cockpit'],['chef','kitchen'],['actor','stage'],['scientist','laboratory'],['librarian','library'],['farmer','field']],
    distractors:['chalk','gavel','aeroplane','recipe','script','microscope','book','tractor'] },
  { rel:'is a part of a',
    pairs:[['petal','flower'],['chapter','book'],['branch','tree'],['wheel','car'],['keyboard','computer'],['string','guitar'],['page','magazine'],['root','plant']],
    distractors:['garden','library','forest','road','screen','music','news','soil'] },
  { rel:'is a kind of a',
    pairs:[['sonnet','poem'],['oak','tree'],['sedan','car'],['violin','instrument'],['emerald','gem'],['sparrow','bird'],['copper','metal'],['tulip','flower'],['cricket','sport']],
    distractors:['rhyme','forest','road','orchestra','ring','flight','wire','garden','bat'] },
  { rel:'is used to',
    pairs:[['thermometer','measure'],['sieve','strain'],['anchor','secure'],['compass','navigate'],['lever','lift'],['filter','purify'],['ladder','climb'],['lock','secure']],
    distractors:['heat','cook','sail','draw','carry','pour','paint','open'] },
  { rel:'becomes, in the extreme,',
    pairs:[['warm','scorching'],['cool','freezing'],['large','colossal'],['small','microscopic'],['sad','devastated'],['happy','ecstatic'],['damp','saturated'],['tired','exhausted']],
    distractors:['mild','chilly','sizeable','petty','gloomy','pleasant','dry','busy'] },
  { rel:'means the opposite of',
    pairs:[['expand','contract'],['ascend','descend'],['praise','criticize'],['gather','scatter'],['conceal','reveal'],['accept','reject'],['permit','forbid'],['create','destroy']],
    distractors:['enlarge','climb','applaud','collect','hide','receive','allow','build'] },
  { rel:'means the same as',
    pairs:[['amplify','increase'],['diminish','reduce'],['conceal','hide'],['rapid','swift'],['sturdy','robust'],['tranquil','peaceful'],['abundant','plentiful'],['perilous','dangerous']],
    distractors:['decrease','enlarge','reveal','slow','fragile','noisy','scarce','safe'] },
  { rel:'produces',
    pairs:[['bee','honey'],['cow','milk'],['hen','egg'],['sheep','wool'],['tree','fruit'],['volcano','lava'],['factory','goods'],['author','book']],
    distractors:['hive','barn','nest','pasture','forest','mountain','machine','library'] },
  { rel:'is where you find',
    pairs:[['library','books'],['orchard','trees'],['aquarium','fish'],['gallery','paintings'],['vineyard','vines'],['armoury','weapons'],['pantry','food'],['archive','records']],
    distractors:['librarian','farmer','water','artist','wine','soldier','chef','clerk'] }
];

// Sentence completion templates: {s: sentence with ___ , a: correct, d:[distractors]}
const SENTENCES = [
  ['The witness gave a ___ account, leaving out nothing of importance.','thorough',['hasty','vague','reluctant']],
  ['Although the evidence seemed strong, the jury remained ___ about his guilt.','uncertain',['convinced','furious','delighted']],
  ['Her explanation was so ___ that even the newest member understood it.','lucid',['convoluted','lengthy','technical']],
  ['The manager was ___ in his praise, mentioning every member of the team.','generous',['sparing','silent','harsh']],
  ['Rather than ___ the problem, the new policy made it considerably worse.','solving',['creating','ignoring','describing']],
  ['The old machinery was ___ and had to be replaced entirely.','obsolete',['modern','valuable','delicate']],
  ['He spoke with such ___ that nobody doubted his sincerity.','conviction',['hesitation','amusement','confusion']],
  ['The report was ___, running to three hundred pages of detail.','exhaustive',['brief','careless','optional']],
  ['Because the deadline was ___, the team worked through the night.','imminent',['distant','flexible','arbitrary']],
  ['She was ___ to accept the offer, having heard troubling rumours.','reluctant',['eager','quick','delighted']],
  ['His argument was ___ by the discovery of new evidence.','undermined',['strengthened','repeated','recorded']],
  ['The instructions were deliberately ___ to prevent any misunderstanding.','explicit',['ambiguous','brief','technical']],
  ['Attendance is ___; every employee must be present.','compulsory',['optional','encouraged','limited']],
  ['The savings were ___ and made almost no difference to the budget.','negligible',['substantial','welcome','unexpected']],
  ['A ___ investor avoids putting everything into a single asset.','prudent',['reckless','wealthy','hasty']],
  ['Support for the proposal was ___, appearing in some regions and not others.','sporadic',['unanimous','constant','enthusiastic']],
  ['The company sought to ___ tensions before they escalated further.','defuse',['inflame','announce','measure']],
  ['His account of the meeting was ___ with what the records showed.','inconsistent',['identical','concerned','satisfied']],
  ['The design was praised for being ___ rather than merely decorative.','functional',['ornate','expensive','colourful']],
  ['She remained ___ throughout the crisis, never once raising her voice.','composed',['frantic','absent','bitter']],
  ['The new evidence served only to ___ the original conclusion.','reinforce',['contradict','delay','obscure']],
  ['The terms were ___, offering advantages to neither side.','equitable',['lopsided','generous','vague']],
  ['Because the data was ___, the team could not draw any conclusion.','incomplete',['thorough','recent','public']],
  ['His ___ approach meant every possibility was tested before deciding.','systematic',['impulsive','casual','narrow']],
  ['The policy was ___ after widespread criticism from staff.','rescinded',['implemented','praised','drafted']],
  ['A ___ reader will notice the contradiction in the second paragraph.','attentive',['distracted','casual','reluctant']],
  ['The results were ___, differing widely from one trial to the next.','inconsistent',['uniform','encouraging','precise']],
  ['The tone of the reply was ___, neither approving nor critical.','neutral',['enthusiastic','scathing','anxious']],
  ['Funding was ___, forcing the project to be scaled back.','curtailed',['expanded','approved','renewed']],
  ['The proposal is ___ given the resources currently available.','impractical',['sensible','popular','urgent']],
  ['He was ___ about the deadline, refusing to consider any extension.','adamant',['flexible','uncertain','cheerful']],
  ['The two accounts are so similar that one appears to ___ the other.','echo',['contradict','precede','replace']],
  ['She has a ___ memory for names and never forgets a face.','remarkable',['poor','selective','fading']],
  ['The audience grew ___ as the speech dragged into its second hour.','restless',['attentive','silent','amused']],
  ['The findings were ___ and require confirmation by further study.','preliminary',['conclusive','published','rejected']],
  ['Costs were ___ by careful planning at every stage.','contained',['inflated','ignored','doubled']],
  ['A ___ observer would have spotted the error immediately.','keen',['casual','distant','hurried']],
  ['His behaviour was ___ with the values the company claims to hold.','incompatible',['consistent','familiar','popular']],
  ['The manual is ___, covering every function of the device.','comprehensive',['selective','outdated','concise']],
  ['She was ___ in her criticism, naming every flaw in the design.','blunt',['tactful','silent','vague']],
  ['The schedule proved too ___ to accommodate the delay.','rigid',['flexible','generous','simple']],
  ['Progress was ___ but steady, with small gains each week.','gradual',['sudden','absent','erratic']],
  ['The claim is ___ and cannot be verified from the records.','unsubstantiated',['documented','obvious','recent']],
  ['A ___ solution would address the cause rather than the symptom.','durable',['temporary','costly','popular']],
  ['The two departments worked in ___, sharing data at every stage.','concert',['isolation','rivalry','secret']]
];

const NONSENSE = ['Zops','Quins','Larks','Trells','Mibs','Vanks','Plims','Grubs','Forns','Delks','Noms','Wexes'];

const OCCUPATIONS = ['engineers','nurses','auditors','pilots','chemists','architects','editors','analysts','surveyors','paramedics'];
const TRAITS = ['work remotely','hold a licence','attend the review','carry a pager','file monthly reports','use the secure system','complete the training','belong to the union'];
const NAMES = ['Ada','Kofi','Mira','Ben','Priya','Tunde','Lena','Omar','Sara','Niall','Cy','Dana','Ravi','Zoe','Ivan','Nadia'];

module.exports = { ANTONYMS, SYNONYMS, ANALOGY_FAMILIES, SENTENCES, NONSENSE, OCCUPATIONS, TRAITS, NAMES };
